services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=auth-db'
      - 'MYSQL_PASSWORD=1'
      - 'MYSQL_ROOT_PASSWORD=1'
      - 'MYSQL_USER=mainuddin'
    ports:
      - '3308:3306'
