spring:
  application:
    name: alumni-auth
  datasource:
    password: 1
    url: jdbc:mysql://localhost:3308/auth-db
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    enabled: true
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"
    enabled: true